name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
        id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
        # Specify the github actions deployment environment
        environment: pub.dev
        # working-directory: path/to/package/within/repository
    # with:
    #   working-directory: path/to/package/within/repository
